global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "triton"
    static_configs:
      - targets: ["triton:8002"]
  - job_name: "node"
    static_configs:
      - targets: ["prometheus:9090"]
