version: "3.9"

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:23.10-py3
    restart: unless-stopped
    command: ["tritonserver", "--model-repository=/models", "--strict-model-config=false"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models:/models

  prometheus:
    image: prom/prometheus:v2.46.0
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.0
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  grafana-data:
