name: icd-ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Run ruff
        run: ruff check . || true
      - name: Run black --check
        run: black --check . || true
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Run unit tests with coverage
        run: |
          pytest -q --cov=icd --cov-report=term-missing --cov-report=xml --cov-fail-under=85 tests/unit
      - name: Store coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  integration:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run integration tests (mock)
        run: pytest -q tests/integration

  perf:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest torch
      - name: Run performance smoke tests
        run: pytest -q tests/perf

  ir-pass:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run IR FileCheck-like tests
        run: pytest -q tests/ir

  stability:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest torch
      - name: Run stability regression tests
        run: pytest -q tests/stability

  package:
    needs: [unit, integration, perf, stability]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build package (sdist/wheel)
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine check dist/*

  publish-testpypi:
    if: startsWith(github.ref, 'refs/tags/')
    needs: package
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Publish to TestPyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: package
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
