name: icd-ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Run ruff
        run: ruff check . || true
      - name: Run black --check
        run: black --check . || true
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run unit tests
        run: pytest -q tests/unit

  integration:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run integration tests (mock)
        run: pytest -q tests/integration

  ir-pass:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test runner
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run IR FileCheck-like tests
        run: pytest -q tests/ir

  package:
    needs: [unit, integration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build package (sdist/wheel)
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine check dist/*
